// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGEoy9crNydAD51EC7SYJf4-dzgUV3y20',
    appId: '1:697531577761:web:2f1d89d9beaf36acc607e0',
    messagingSenderId: '697531577761',
    projectId: 'tanjimshop-99362',
    authDomain: 'tanjimshop-99362.firebaseapp.com',
    storageBucket: 'tanjimshop-99362.firebasestorage.app',
    measurementId: 'G-JE9HL36KGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABQq1P9GleJ7rtlnL2jFcocucEJiNXEeo',
    appId: '1:697531577761:android:9cc865791f669e06c607e0',
    messagingSenderId: '697531577761',
    projectId: 'tanjimshop-99362',
    storageBucket: 'tanjimshop-99362.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGEoy9crNydAD51EC7SYJf4-dzgUV3y20',
    appId: '1:697531577761:web:29151990bcddca5fc607e0',
    messagingSenderId: '697531577761',
    projectId: 'tanjimshop-99362',
    authDomain: 'tanjimshop-99362.firebaseapp.com',
    storageBucket: 'tanjimshop-99362.firebasestorage.app',
    measurementId: 'G-4P6S12ST4T',
  );
}
